"""add ingestion_run model

Revision ID: 0ddafab8862f
Revises: 8ff0b2d0d5aa
Create Date: 2026-03-01 08:45:25.219261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddafab8862f'
down_revision: Union[str, None] = '8ff0b2d0d5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_started_at', sa.DateTime(), nullable=True),
    sa.Column('run_ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_added', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
