"""Add connpass_api to SourceType

Revision ID: 8ff0b2d0d5aa
Revises: abcff8477f2d
Create Date: 2026-02-28 16:26:30.157317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff0b2d0d5aa'
down_revision: Union[str, None] = 'abcff8477f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sourcetype ADD VALUE 'connpass_api'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Postgres doesn't easily allow dropping enum values. 
    pass
    # ### end Alembic commands ###
